import LenisProvider from "@/providers/lenis-provider";
import type { Metadata } from "next";
import { Noto_Serif_Display } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";

const notoSerifDisplay = Noto_Serif_Display({
  subsets: ["latin"],
  weight: "variable",
  style: ["normal", "italic"],
  variable: "--font-noto-serif-display",
  display: "swap",
  axes: ["wdth"],
});

const aileron = localFont({
  src: [
    {
      path: "../../public/fonts/aileron-regular.woff",
      weight: "400",
      style: "normal",
    },
    {
      path: "../../public/fonts/aileron-semibold.woff",
      weight: "600",
      style: "normal",
    },
    {
      path: "../../public/fonts/aileron-semibold-italic.woff",
      weight: "600",
      style: "italic",
    },
    {
      path: "../../public/fonts/aileron-bold.woff",
      weight: "700",
      style: "normal",
    },
  ],
  variable: "--font-aileron",
  display: "swap",
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${aileron.variable} ${notoSerifDisplay.variable} antialiased`}
      >
        <LenisProvider>
          <main className="max-w-[1920px] mx-auto">{children}</main>
        </LenisProvider>
      </body>
    </html>
  );
}
